version: '3.8'

services:
  postgres:
    image: postgres:11.10-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  postgres-test:
    image: postgres:11.10-alpine
    restart: always
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  server:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./data/coverage:/mcc-server/data/coverage
      - ./data/report:/mcc-server/data/report
    environment:
      - PORT
      - ENABLE_CORS
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT
      - POSTGRES_TEST_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD